/*
 * Copyright (c) 2025 AMD. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_RISCV_APLIC_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_RISCV_APLIC_H_

#define IRQ_TYPE_NONE           0
#define IRQ_TYPE_DETACHED       1
#define IRQ_TYPE_EDGE_RISING    4
#define IRQ_TYPE_EDGE_FALLING   5
#define IRQ_TYPE_LEVEL_HIGH     6
#define IRQ_TYPE_LEVEL_LOW      7

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_RISCV_APLIC_H_ */
